global using System.Data;
global using SFCTOFC.DailySalesPlanManagement.Application.Common.Interfaces;
global using SFCTOFC.DailySalesPlanManagement.Application.Common.Models;
global using SFCTOFC.DailySalesPlanManagement.Application.Common.Extensions;
global using SFCTOFC.DailySalesPlanManagement.Domain.Entities;
global using FluentValidation;
global using Microsoft.AspNetCore.Components;
global using MudBlazor;
global using Microsoft.EntityFrameworkCore;
